### ISSUE TITLE
Is it possible to initialize a ciphertext with input from stdin?

### ISSUE THREAD

**Issue by ramym1** [momalab/e3#10]
Hi,
in the tutorials I read hard-coded values are used as inputs.
Is there a way to read input from stdin or from a file into e3 ciphertexts?
Thanks!

**Comment by mazonka** [comment]
Yes it is possible. CGT tool can encrypt and decrypt (with secret keys) values. The encrypted variable can be initialized from a string representing its encrypted value. Therefore, the number can be encrypted with CGT, stored as a file (ASCII), then read by the program as a string into the variable. Let me know, if it is still confusing.

**Comment by ramym1** [comment]
This is clear, thanks for your answer
