### ISSUE TITLE
SEAL CKKS configuration

### ISSUE THREAD

**Issue by jimouris** [momalab/e3#12]
Hi,

I'm trying to run SEAL CKKS by replacing the `bfv` from [this configuration](https://github.com/momalab/e3/blob/master/tutorials/bench/batch/cgt_seal.cfg) to `ckks` but it throws multiple errors.

Is there any example configuration to run SEAL with CKKS?

**Comment by jimouris** [comment]
cc: @cgouert

**Comment by mazonka** [comment]
Currently, bridging is not implemented with CKKS. We may implement it in the future.

**Comment by jimouris** [comment]
Thank you for the clarification. Do you support SEAL CKKS for regular FP arithmetic (no bridging)? If so, can you provide a barebones configuration?
