### ISSUE TITLE
Error in installing Palisade library

### ISSUE THREAD

**Issue by Kitt-D** [momalab/e3#13]
When I am running "make PALI" in e3/3p, I am getting these errors-

/usr/bin/ld: /usr/local/lib/libntl.a(ZZ.o): relocation R_X86_64_TPOFF32 against `_ZN3NTLL8iodigitsE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libntl.a(fileio.o): relocation R_X86_64_TPOFF32 against `_ZZN3NTL8UniqueIDB5cxx11EvE37_ntl_hidden_variable_tls_local_ptr_ID' can not be used when making a shared object; recompile with -fPIC

Where exactly should I add -fPIC flag in code to fix this?

**Comment by Kitt-D** [comment]
I see that this is caused when the Makefile inside "$palipath/build/" is run. But this is run when I run the default "make PALI" in e3/3p, so not sure what is the issue.

**Comment by JustKshitijD** [comment]
Turns out this is actually an issue with NTL installation which needs to be installed with SHARED=on. 
Apologies for inconvenience. You may close this issue.
