### ISSUE TITLE
SEAL code not building

### ISSUE THREAD

**Issue by JustKshitijD** [momalab/e3#14]
I was able to install libraries via 'make SEAL', 'make PALI', etc. in e3/3p; and also able to run examples/palisade.
But when in e3/src, I run- "make alice USER=../tutorials/basic SEAL=1", I am getting the below error- 

`make[1]: Entering directory '$HOME/e3/src'
unx
echo ./cgt.exe gen -c ../tutorials/basic/cgt.cfg -d ../tutorials/basic
./cgt.exe gen -c ../tutorials/basic/cgt.cfg -d ../tutorials/basic
./cgt.exe gen -c ../tutorials/basic/cgt.cfg -d ../tutorials/basic
cgt: generating for unx
Generating private key .. ok
Generating evaluation key .. cgt: failed, cleaning up
working dir: $HOME/e3/src
cgt error (str): err at cpp_cgt/keys/sk_seal1.cpp:96 [No integer encoder supported for this SEAL version]
make[1]: *** [mak_sec.mak:17: secint.inc] Error 1
`

So, my SEAL code is not building. Please help to resolve this.

**Comment by mazonka** [comment]
I can reproduce this error. Working on it..

**Comment by educhielle** [comment]
We have fixed this tutorial, but have not fixed the other tutorials yet.

The issue was if the new version of SEAL which is not compatible with the previously supported version.
