### ISSUE TITLE
SEAL problem on bridging tutorial (even with the version in paper and updated commit)

### ISSUE THREAD

**Issue by hyerinshelly** [momalab/e3#16]
Hello,

I'm interested in the experiment shown in your paper, but struggling with tutorial.

**I've tried on the commit 9fb718f** which is mentioned in your ICCAD '22 paper, but **bridging bench is not working due to the error related to SEAL**. I already went through and saw the issue(#14) with building SEAL. This is why I tried on the commit of paper version. However, I couldn't still run the bridging example on the tutorial. The error message indicates that the number of arguments of `std::streamoff seal::Ciphertext::load` does not coincidence (The full error message at below). Would this be also related with the same issue which seems you are working on currently?
```
./../3p/seal_unx/include/seal/ciphertext.h:517:31: note:   no known conversion for argument 1 from 'const std::shared_ptr<seal::SEALContext>' to 'const seal::SEALContext&'
./../3p/seal_unx/include/seal/ciphertext.h:588:31: note: candidate: 'std::streamoff seal::Ciphertext::load(const seal::SEALContext&, const seal_byte*, std::size_t)'
         inline std::streamoff load(const SEALContext &context, const seal_byte *in, std::size_t size)
                               ^~~~
./../3p/seal_unx/include/seal/ciphertext.h:588:31: note:   candidate expects 3 arguments, 2 provided
make[1]: *** [mak_cgt.mak:70: bn_unx/def_seal1.o] Error 1
make[1]: Leaving directory '/workspace/e3/src'
make: *** [makefile:31: cgt.exe] Error 2
```

Additionally, yesterday I found that you made some update on files related with SEAL a few days ago, so I made a pull and tried again. I'm attaching my new error message when running again the bridging tutorial with pulled version, since the content of message is changed from the previous(#14). It looks like that you are still working on the SEAL problem, but just in case, I wanted to let you know the updated error.
```
./../3p/seal_unx/include/seal/util/ntt.h: In function 'void seal::util::inverse_ntt_negacyclic_harvey(seal::util::PolyIter, std::size_t, seal::util::ConstNTTTablesIter)':
./../3p/seal_unx/include/seal/util/defines.h:164:27: error: 'for_each_n' is not a member of 'std'
 #define SEAL_ITERATE std::for_each_n
                           ^~~~~~~~~~
./../3p/seal_unx/include/seal/util/ntt.h:335:13: note: in expansion of macro 'SEAL_ITERATE'
             SEAL_ITERATE(
             ^~~~~~~~~~~~
./../3p/seal_unx/include/seal/util/defines.h:164:27: note: suggested alternative: 'for_each'
 #define SEAL_ITERATE std::for_each_n
                           ^~~~~~~~~~
./../3p/seal_unx/include/seal/util/ntt.h:335:13: note: in expansion of macro 'SEAL_ITERATE'
             SEAL_ITERATE(
             ^~~~~~~~~~~~
make[1]: *** [mak_cgt.mak:78: bn_unx/def_seal1.o] Error 1
make[1]: Leaving directory '/workspace/e3/src'
make: *** [makefile:32: cgt.exe] Error 2
```

Any comments would be helpful for me!

**Comment by educhielle** [comment]
The issue is with the SEAL library version. The configuration file used in the tutorials is for SEAL version 3.3.2, but now E3 uses SEAL 3.7 as the default option. We have been slowly updating the tutorials to work with the newer version. I suppose a quick fix is to simply replace the encoder in the cgt file from 'integer' to 'batch' since SEAL 3.7 does not support the former encoder.

In any case, I see you are interested in the benchmarks used in ICCAD. The ones currently available in the public repository are not the ones used for ICCAD's paper. I will prepare a readme and upload those to the public repository in the following days. They have been tested with SEAL 3.7.

**Comment by educhielle** [comment]
Alright. Please, check e3/benchmarks/bridging for the benchmarks used in ICCAD's paper.

**Comment by hyerinshelly** [comment]
I really appreciate for your quick response! I took a look at the benchmark directory and again tried running with.

Sorry to say this, it reproduces exactly same error (regarding to 'for_each_n'), even though I checked the cgt file having 'batch' option instead of 'integer'. 

Then what the problem could be? (I guess the version of SEAL is not the one..) Thanks, again!
