### ISSUE TITLE
Errors while running `make check`

### ISSUE THREAD

**Issue by pjattke** [momalab/e3#4]
Hi, I receive the following errors when running `make check` after I have successfully built E3 using `make` and also installed all target libraries using the scripts provided in the `3p` folder:

```
./secint.inc:28:13: error: no match for 'operator<<' (operand types are 'const NativeUint<64>' and 'int')
   28 |     T y = x << 1;
      |           ~~^~~~
./secint.inc:28:16: error: invalid user-defined conversion from 'int' to 'const NativeUint<64>&' [-fpermissive]
   28 |     T y = x << 1;
      |                ^
./secint.inc:28:16: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
   28 |     T y = x << 1;
      |                ^
      |                |
      |                int
./secint.inc:28:16: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
In file included from ./e3int.h:4,
                 from user/def/func.h:3,
                 from user/def/main.cpp:4:

...

make[2]: *** [mak_alice.mak:52: alice.exe] Error 1
make[1]: *** [makefile:45: alice.exe] Error 2
[################################################## (100%)]
./check_unx.sh: line 463: ./alice.exe: No such file or directory


Step 2
=== e3 === check GAT for Gates
Generating cgt.exe...
[                                                   (1%)] In file included from /usr/include/assert.h:35,
                 from cpp_crcl/d1/util.h:70,
                 from cpp_crcl/d1/cpu_stats.c:66:
/usr/include/features.h:187:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
  187 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      |   ^~~~~~~
[################################################## (100%)]
Compiling...
ls: cannot access 'bob.exe': No such file or directory
make: *** [makefile:73: check] Error 2
```
Thereafter, the process aborts. However, manually building and running an example (e.g., `user/fibo`) as described in your [README](https://github.com/momalab/e3/tree/master/doc#manual-build-using-cgtexe) works without any problem. However, trying to do the same by using the Makefiles does not work as `bob.exe` is not built.

You can find the Dockerimage I am using where all the deps are installed, here: [base_e3](https://hub.docker.com/repository/docker/marblehe/base_e3).

**Comment by pjattke** [comment]
As this was related to an older release of E3, this issue can be closed.

**Comment by mazonka** [comment]
The script that checks some functions has been removed from makefile. However the error that you posted refer to the implementation of native type. I was able to reproduce those errors. I added the test in src/user/ops and fixed the code.
