### ISSUE TITLE
Tutorial | Step 4: Question about Alice's result

### ISSUE THREAD

**Issue by pjattke** [momalab/e3#5]
In Step 4 of your [tutorial](https://github.com/momalab/e3/blob/master/README.md#step-4-alices-computation) you state:

> And in your project directory
> ```
>     cp $E3/src/e3int.h ./
>     cp $E3/src/e3key.h ./
>     cp $E3/src/cgtshared.* ./
>     cp $E3/src/cgtkey.* ./
>     $E3/src/cgt.exe gen -r $E3/src
>     g++ -std=c++17 -DE3KEY=1 a.cpp secint.cpp cgtshared.cpp cgtkey.cpp -o alice.exe
>     ./alice.exe
> ```
> Should print 6.

However, executing this prints:
```
Secure[0,1,1,0,0,0,0,0]
```

I assume that is because the result is still encrypted because in the demo code (file `a.cpp`) no decryption of the computed result is included.

**Comment by mazonka** [comment]
I have fixed the description, to reflect that. The source files were correct.
