### ISSUE TITLE
Rotation support

### ISSUE THREAD

**Issue by pjattke** [momalab/e3#9]
Hi momalab,

The fact that E3 supports batching is great! We could, however, not find any method to rotate a batched ciphertext. Does there exist a way to rotate a ciphertext in E3? Rotations are essential for batching as data is not always optimally arranged for a batched computation.

Thank you very much!

**Comment by mazonka** [comment]
At this moment we do not have such function. But we will implement it in the future.

**Comment by educhielle** [comment]
rotation is now supported with rotate_rows and rotate_columns:
```
        $Name & rotate_columns();
        $Name & rotate_rows(size_t s);
        static $Name rotate_columns(const $Name & a);
        static $Name rotate_rows(const $Name & a, size_t s);
```
where $Name is a placeholder for the Secure class name
